export async function generateAIText(prompt, apiKey, provider = 'openai') {
    if (!apiKey) {
        throw new Error("No API key provided. Please configure it in settings.")
    }

    try {
        if (provider === 'gemini') {
            const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`
            const response = await fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: {
                        temperature: 0.7,
                        responseMimeType: "application/json"
                    }
                })
            })

            if (!response.ok) {
                const errorData = await response.json()
                throw new Error(errorData.error?.message || "Failed to generate content from Gemini")
            }

            const data = await response.json()
            return data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated."

        } else {
            // Default to OpenAI
            const url = 'https://api.openai.com/v1/chat/completions'
            const response = await fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${apiKey}`,
                },
                body: JSON.stringify({
                    model: 'gpt-4o-mini',
                    response_format: { type: "json_object" },
                    messages: [{ role: 'user', content: prompt }],
                    temperature: 0.7,
                })
            })

            if (!response.ok) {
                const errorData = await response.json()
                throw new Error(errorData.error?.message || "Failed to generate content from OpenAI")
            }

            const data = await response.json()
            return data.choices?.[0]?.message?.content || "No response generated."
        }
    } catch (error) {
        console.error("AI Generation Error:", error)
        throw error
    }
}

/**
 * Robustly parses a JSON string generated by an AI, handling common malformed issues.
 */
export function parseAIJsonResponse(rawText) {
    if (!rawText) throw new Error("Empty response from AI")

    let cleaned = rawText.trim()

    // 1. Remove markdown code blocks if present
    cleaned = cleaned.replace(/^```json\s*/im, '')
    cleaned = cleaned.replace(/^```\s*/im, '')
    cleaned = cleaned.replace(/```\s*$/im, '')

    // 2. Sometimes the AI adds conversational intro/outro text.
    // We try to extract just the first JSON object/array we can find.
    const firstBrace = cleaned.indexOf('{')
    const firstBracket = cleaned.indexOf('[')

    let startIndex = -1
    let isArray = false

    if (firstBrace !== -1 && firstBracket !== -1) {
        startIndex = Math.min(firstBrace, firstBracket)
        isArray = startIndex === firstBracket
    } else if (firstBrace !== -1) {
        startIndex = firstBrace
    } else if (firstBracket !== -1) {
        startIndex = firstBracket
        isArray = true
    }

    if (startIndex !== -1) {
        // Find the matching closing bracket/brace
        const endChar = isArray ? ']' : '}'
        const endIndex = cleaned.lastIndexOf(endChar)

        if (endIndex !== -1 && endIndex > startIndex) {
            cleaned = cleaned.substring(startIndex, endIndex + 1)
        }
    }

    try {
        return JSON.parse(cleaned)
    } catch (err) {
        console.error("Failed to parse JSON after cleaning. Raw Text:", rawText)
        throw new Error("The AI returned a malformed response that couldn't be parsed.")
    }
}
